### ISSUE TITLE
Typo in listing 2 haveBirthday function implementation

### ISSUE THREAD

**Issue by rendstrasser** [chriskiehl/Data-Oriented-Programming-In-Java-Book#1]
I believe there is a + 1 missing in this line:

https://github.com/chriskiehl/Data-Oriented-Programming-In-Java-Book/blob/195b325917784524d395c00d8c37a69583ad1a66/app/src/test/java/dop/chapter02/Listings.java#L837

**Comment by chriskiehl** [comment]
Great catch! Fixed! 👍
